server {
    listen 443 ssl;
    server_name 192.168.122.17;

    ssl_certificate     /etc/nginx/certs/192.168.122.17.pem;
    ssl_certificate_key /etc/nginx/certs/192.168.122.17-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://front-toolrent:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host; 
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;  
        proxy_set_header X-Forwarded-For $remote_addr;
    }

   # KEYCLOAK
    location /realms/ {
        proxy_pass http://keycloak:8080/realms/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $remote_addr;
    }

    location /resources/ {
        proxy_pass http://keycloak:8080/resources/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
    }
   location /admin/ {
        proxy_pass http://keycloak:8080/admin/;   
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
   location /api/ {
        proxy_pass http://app-toolrent:8080/api/; # OJO: Puerto interno de Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
